// Generated by Claude Haiku 4.5
const fs = require('fs');
const path = require('path');

const distDir = path.join(__dirname, 'dist-sandbox');
const sandboxDir = path.join(__dirname, 'sandbox');
const glowscriptOfflineDir = path.join(__dirname, 'GlowScriptOffline');

// Remove dist-sandbox if it exists
if (fs.existsSync(distDir)) {
  fs.rmSync(distDir, { recursive: true, force: true });
  console.log(`Removed old ${distDir}`);
}

// Create dist-sandbox
fs.mkdirSync(distDir, { recursive: true });
console.log(`Created ${distDir}`);

// Helper function to copy directories recursively
function copyDir(src, dest) {
  if (!fs.existsSync(src)) {
    console.warn(`Source not found: ${src}`);
    return;
  }
  
  fs.mkdirSync(dest, { recursive: true });
  const files = fs.readdirSync(src);
  
  files.forEach(file => {
    const srcPath = path.join(src, file);
    const destPath = path.join(dest, file);
    const stat = fs.statSync(srcPath);
    
    if (stat.isDirectory()) {
      copyDir(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  });
}

// Copy sandbox contents
copyDir(sandboxDir, distDir);
console.log(`Copied sandbox contents to ${distDir}`);

// Copy glowscript_libraries folder
copyDir(path.join(glowscriptOfflineDir, 'glowscript_libraries'), path.join(distDir, 'glowscript_libraries'));
console.log(`Copied glowscript_libraries to ${distDir}`);

// Copy GlowScript.html
fs.copyFileSync(path.join(glowscriptOfflineDir, 'GlowScript.html'), path.join(distDir, 'GlowScript.txt'));
console.log(`Copied GlowScript.html to ${distDir}`);

console.log('Build complete!');
